// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr1RMURDBicraYxuBw6hVkVhLM0OkgtqE',
    appId: '1:931730877246:web:237d087a389691df8d9a6f',
    messagingSenderId: '931730877246',
    projectId: 'geolocationapp-87c34',
    authDomain: 'geolocationapp-87c34.firebaseapp.com',
    storageBucket: 'geolocationapp-87c34.appspot.com',
    measurementId: 'G-QHX6M67E8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjOz3WvuD0qYP-RWcg-aUUBezb1bX9unc',
    appId: '1:931730877246:android:b99a49a2821429ae8d9a6f',
    messagingSenderId: '931730877246',
    projectId: 'geolocationapp-87c34',
    storageBucket: 'geolocationapp-87c34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3nJN3AS2zboOBSfu5Za28ejo8al4YjDs',
    appId: '1:931730877246:ios:14a00b80daba5d458d9a6f',
    messagingSenderId: '931730877246',
    projectId: 'geolocationapp-87c34',
    storageBucket: 'geolocationapp-87c34.appspot.com',
    iosBundleId: 'com.example.beybicoAdmin',
  );
}
